Adding Type Annotations
hackebrot/pytest-md pull request #14
Opened 2019-07-30 16:50 UTC by ssd71

I did some trivial type annotations but I can't seem to be getting any further. Can you please review these changes? In addition to these changes, I also attempted to add type annotations to arguments like config, terminalreporter, report by importing the required modules from _pytest, but it didn't stand with tox. What do you suggest?

2019-07-30 17:27 UTC, hackebrot requested changes
Thanks for working on this @ssd71! 📝 I added a suggestion to your pull-request.

I do not recommend adding any annotations to variables that we don't have control over.

2019-07-30 17:27 UTC, hackebrot commented on src/pytest_md/plugin.py
> +            reports_by_file: Dict[Outcome, List] = collections.defaultdict(list)
We group lists of reports by test file here:

```suggestion
            reports_by_file: Dict[str, List] = collections.defaultdict(list)
```

2019-07-31 06:38 UTC, ssd71 commented
Could you help me judge where I should put in type annotations?

2019-08-08 09:14 UTC, hackebrot commented
Hi @ssd71! 👋 

We can merge your pull-request as is and if we feel we need more type annotations, we can always add them later since they're optional in Python.

Thanks again for your contribution! 📝

2019-08-08 09:14 UTC, hackebrot approved these changes
LGTM 🚀

2019-08-08 09:15 UTC, merged